#ifndef __MODEL_PROCESS_ERROE_MODULE_H__
#define __MODEL_PROCESS_ERROE_MODULE_H__

enum
{
	IFLYPEDU_SUCCESS = 0,
    IFLYPEDU_ERROR_GENERAL,
    IFLYPEDU_ERROR_BASE = 120000,
    IFLYPEDU_ERROR_INVAILD_PARAMS = 120002,
    IFLYPEDU_ERROR_OPEN_FILE_FAILED,
    IFLYPEDU_ERROR_CONF_FORMAT_UNSUPPORTED,
    IFLYPEDU_ERROR_MODEL_TYPE_UNSUPPORTED,
    IFLYPEDU_ERROR_MEM_ALLOC,
    IFLYPEDU_ERROR_NULL_PTR,
};

#endif




