set(CMAKE_SYSTEM_NAME QNX)
set(arch gcc_ntoarmv7le)
#set(SUBARCH arm)

set(CMAKE_C_COMPILER qcc)
set(CMAKE_C_COMPILER_TARGET ${arch})
set(CMAKE_CXX_COMPILER qcc)
set(CMAKE_CXX_COMPILER_TARGET ${arch})

set(CMAKE_AR qcc CACHE FILEPATH "Archiver")
set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> -Vgcc_ntoarmv7le -a <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> -Vgcc_ntoarmv7le -a <TARGET> <LINK_FLAGS> <OBJECTS>")

set( CMAKE_FIND_ROOT_PATH ${QNX_TARGET} )
set( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
set( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
set( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )


