#ifndef __IFLYTEK_CV3_PACK_UNPACK_ERROR_MODULE_H__
#define __IFLYTEK_CV3_PACK_UNPACK_ERROR_MODULE_H__

enum
{
	IFLYPU_SUCCESS = 0,
    IFLYPU_ERROR_GENERAL,
    IFLYPU_ERROR_INVAILD_PARAMS,
    IFLYPU_ERROR_OPEN_FILE_FAILED,
    IFLYPU_ERROR_CONF_FORMAT_UNSUPPORTED,
    IFLYPU_ERROR_MODEL_TYPE_UNSUPPORTED,
    IFLYPU_ERROR_MEM_ALLOC,
    IFLYPU_ERROR_NULL_PTR,
};

#endif




